/**
 * <copyright>
 * </copyright>
 *
 * 
 */
package org.qualitune.jouleunit.android.testrun.resource.testrun.grammar;

public class TestrunGrammarInformationProvider {
	
	public final static org.eclipse.emf.ecore.EStructuralFeature ANONYMOUS_FEATURE = org.eclipse.emf.ecore.EcoreFactory.eINSTANCE.createEAttribute();
	static {
		ANONYMOUS_FEATURE.setName("_");
	}
	
	public final static TestrunGrammarInformationProvider INSTANCE = new TestrunGrammarInformationProvider();
	
	private java.util.Set<String> keywords;
	
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunKeyword TESTRUN_0_0_0_0 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunKeyword("TestRun", org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.ONE);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunWhiteSpace TESTRUN_0_0_0_1 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunWhiteSpace(1, org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.ONE);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunPlaceholder TESTRUN_0_0_0_2 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunPlaceholder(org.qualitune.jouleunit.android.testrun.TestrunPackage.eINSTANCE.getTestRun().getEStructuralFeature(org.qualitune.jouleunit.android.testrun.TestrunPackage.TEST_RUN__NAME), "TEXT", org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.ONE, 0);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunLineBreak TESTRUN_0_0_0_3 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunLineBreak(org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.ONE, 0);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunKeyword TESTRUN_0_0_0_4_0_0_0 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunKeyword("applicationUnderTest", org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.ONE);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunWhiteSpace TESTRUN_0_0_0_4_0_0_1 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunWhiteSpace(1, org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.ONE);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunKeyword TESTRUN_0_0_0_4_0_0_2 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunKeyword(":", org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.ONE);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunWhiteSpace TESTRUN_0_0_0_4_0_0_3 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunWhiteSpace(1, org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.ONE);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunPlaceholder TESTRUN_0_0_0_4_0_0_4 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunPlaceholder(org.qualitune.jouleunit.android.testrun.TestrunPackage.eINSTANCE.getTestRun().getEStructuralFeature(org.qualitune.jouleunit.android.testrun.TestrunPackage.TEST_RUN__AUT), "QUOTED_34_34", org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.ONE, 0);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunWhiteSpace TESTRUN_0_0_0_4_0_0_5 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunWhiteSpace(1, org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.ONE);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunPlaceholder TESTRUN_0_0_0_4_0_0_6 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunPlaceholder(org.qualitune.jouleunit.android.testrun.TestrunPackage.eINSTANCE.getTestRun().getEStructuralFeature(org.qualitune.jouleunit.android.testrun.TestrunPackage.TEST_RUN__PACKAGE_UNDER_TEST), "PACKAGE", org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.ONE, 0);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunLineBreak TESTRUN_0_0_0_4_0_0_7 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunLineBreak(org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.ONE, 0);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunSequence TESTRUN_0_0_0_4_0_0 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunSequence(org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.ONE, TESTRUN_0_0_0_4_0_0_0, TESTRUN_0_0_0_4_0_0_1, TESTRUN_0_0_0_4_0_0_2, TESTRUN_0_0_0_4_0_0_3, TESTRUN_0_0_0_4_0_0_4, TESTRUN_0_0_0_4_0_0_5, TESTRUN_0_0_0_4_0_0_6, TESTRUN_0_0_0_4_0_0_7);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunChoice TESTRUN_0_0_0_4_0 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunChoice(org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.ONE, TESTRUN_0_0_0_4_0_0);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCompound TESTRUN_0_0_0_4 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCompound(TESTRUN_0_0_0_4_0, org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.QUESTIONMARK);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunKeyword TESTRUN_0_0_0_5_0_0_0 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunKeyword("unitTests", org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.ONE);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunWhiteSpace TESTRUN_0_0_0_5_0_0_1 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunWhiteSpace(1, org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.ONE);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunKeyword TESTRUN_0_0_0_5_0_0_2 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunKeyword(":", org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.ONE);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunWhiteSpace TESTRUN_0_0_0_5_0_0_3 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunWhiteSpace(1, org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.ONE);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunPlaceholder TESTRUN_0_0_0_5_0_0_4 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunPlaceholder(org.qualitune.jouleunit.android.testrun.TestrunPackage.eINSTANCE.getTestRun().getEStructuralFeature(org.qualitune.jouleunit.android.testrun.TestrunPackage.TEST_RUN__JUNIT_APK), "QUOTED_34_34", org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.ONE, 0);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunWhiteSpace TESTRUN_0_0_0_5_0_0_5 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunWhiteSpace(1, org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.ONE);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunPlaceholder TESTRUN_0_0_0_5_0_0_6 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunPlaceholder(org.qualitune.jouleunit.android.testrun.TestrunPackage.eINSTANCE.getTestRun().getEStructuralFeature(org.qualitune.jouleunit.android.testrun.TestrunPackage.TEST_RUN__JUNIT_PACKAGE), "PACKAGE", org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.ONE, 0);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunLineBreak TESTRUN_0_0_0_5_0_0_7 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunLineBreak(org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.ONE, 0);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunSequence TESTRUN_0_0_0_5_0_0 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunSequence(org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.ONE, TESTRUN_0_0_0_5_0_0_0, TESTRUN_0_0_0_5_0_0_1, TESTRUN_0_0_0_5_0_0_2, TESTRUN_0_0_0_5_0_0_3, TESTRUN_0_0_0_5_0_0_4, TESTRUN_0_0_0_5_0_0_5, TESTRUN_0_0_0_5_0_0_6, TESTRUN_0_0_0_5_0_0_7);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunChoice TESTRUN_0_0_0_5_0 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunChoice(org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.ONE, TESTRUN_0_0_0_5_0_0);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCompound TESTRUN_0_0_0_5 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCompound(TESTRUN_0_0_0_5_0, org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.QUESTIONMARK);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunKeyword TESTRUN_0_0_0_6_0_0_0 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunKeyword("numberOfRuns", org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.ONE);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunWhiteSpace TESTRUN_0_0_0_6_0_0_1 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunWhiteSpace(1, org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.ONE);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunKeyword TESTRUN_0_0_0_6_0_0_2 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunKeyword(":", org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.ONE);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunWhiteSpace TESTRUN_0_0_0_6_0_0_3 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunWhiteSpace(1, org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.ONE);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunPlaceholder TESTRUN_0_0_0_6_0_0_4 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunPlaceholder(org.qualitune.jouleunit.android.testrun.TestrunPackage.eINSTANCE.getTestRun().getEStructuralFeature(org.qualitune.jouleunit.android.testrun.TestrunPackage.TEST_RUN__NO_OF_RUNS), "NUMBER", org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.ONE, 0);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunLineBreak TESTRUN_0_0_0_6_0_0_5 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunLineBreak(org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.ONE, 0);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunSequence TESTRUN_0_0_0_6_0_0 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunSequence(org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.ONE, TESTRUN_0_0_0_6_0_0_0, TESTRUN_0_0_0_6_0_0_1, TESTRUN_0_0_0_6_0_0_2, TESTRUN_0_0_0_6_0_0_3, TESTRUN_0_0_0_6_0_0_4, TESTRUN_0_0_0_6_0_0_5);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunChoice TESTRUN_0_0_0_6_0 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunChoice(org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.ONE, TESTRUN_0_0_0_6_0_0);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCompound TESTRUN_0_0_0_6 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCompound(TESTRUN_0_0_0_6_0, org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.QUESTIONMARK);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunKeyword TESTRUN_0_0_0_7_0_0_0 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunKeyword("idleTime", org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.ONE);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunWhiteSpace TESTRUN_0_0_0_7_0_0_1 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunWhiteSpace(1, org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.ONE);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunKeyword TESTRUN_0_0_0_7_0_0_2 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunKeyword(":", org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.ONE);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunWhiteSpace TESTRUN_0_0_0_7_0_0_3 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunWhiteSpace(1, org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.ONE);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunPlaceholder TESTRUN_0_0_0_7_0_0_4 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunPlaceholder(org.qualitune.jouleunit.android.testrun.TestrunPackage.eINSTANCE.getTestRun().getEStructuralFeature(org.qualitune.jouleunit.android.testrun.TestrunPackage.TEST_RUN__IDLE_TIME), "NUMBER", org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.ONE, 0);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunLineBreak TESTRUN_0_0_0_7_0_0_5 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunLineBreak(org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.ONE, 0);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunSequence TESTRUN_0_0_0_7_0_0 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunSequence(org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.ONE, TESTRUN_0_0_0_7_0_0_0, TESTRUN_0_0_0_7_0_0_1, TESTRUN_0_0_0_7_0_0_2, TESTRUN_0_0_0_7_0_0_3, TESTRUN_0_0_0_7_0_0_4, TESTRUN_0_0_0_7_0_0_5);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunChoice TESTRUN_0_0_0_7_0 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunChoice(org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.ONE, TESTRUN_0_0_0_7_0_0);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCompound TESTRUN_0_0_0_7 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCompound(TESTRUN_0_0_0_7_0, org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.QUESTIONMARK);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunKeyword TESTRUN_0_0_0_8_0_0_0 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunKeyword("hardwareProfiling", org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.ONE);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunWhiteSpace TESTRUN_0_0_0_8_0_0_1 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunWhiteSpace(1, org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.ONE);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunKeyword TESTRUN_0_0_0_8_0_0_2 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunKeyword(":", org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.ONE);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunWhiteSpace TESTRUN_0_0_0_8_0_0_3 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunWhiteSpace(1, org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.ONE);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunBooleanTerminal TESTRUN_0_0_0_8_0_0_4 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunBooleanTerminal(org.qualitune.jouleunit.android.testrun.TestrunPackage.eINSTANCE.getTestRun().getEStructuralFeature(org.qualitune.jouleunit.android.testrun.TestrunPackage.TEST_RUN__HARDWARE_PROFILING_ON), "on", "off", org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.ONE, 0);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunLineBreak TESTRUN_0_0_0_8_0_0_5 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunLineBreak(org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.ONE, 0);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunSequence TESTRUN_0_0_0_8_0_0 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunSequence(org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.ONE, TESTRUN_0_0_0_8_0_0_0, TESTRUN_0_0_0_8_0_0_1, TESTRUN_0_0_0_8_0_0_2, TESTRUN_0_0_0_8_0_0_3, TESTRUN_0_0_0_8_0_0_4, TESTRUN_0_0_0_8_0_0_5);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunChoice TESTRUN_0_0_0_8_0 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunChoice(org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.ONE, TESTRUN_0_0_0_8_0_0);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCompound TESTRUN_0_0_0_8 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCompound(TESTRUN_0_0_0_8_0, org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.QUESTIONMARK);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunKeyword TESTRUN_0_0_0_9_0_0_0 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunKeyword("run", org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.ONE);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunWhiteSpace TESTRUN_0_0_0_9_0_0_1 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunWhiteSpace(1, org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.ONE);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunKeyword TESTRUN_0_0_0_9_0_0_2 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunKeyword(":", org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.ONE);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunWhiteSpace TESTRUN_0_0_0_9_0_0_3 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunWhiteSpace(1, org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.ONE);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunBooleanTerminal TESTRUN_0_0_0_9_0_0_4 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunBooleanTerminal(org.qualitune.jouleunit.android.testrun.TestrunPackage.eINSTANCE.getTestRun().getEStructuralFeature(org.qualitune.jouleunit.android.testrun.TestrunPackage.TEST_RUN__REMOTE_RUN), "onServer", "local", org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.ONE, 0);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunLineBreak TESTRUN_0_0_0_9_0_0_5 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunLineBreak(org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.ONE, 0);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunSequence TESTRUN_0_0_0_9_0_0 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunSequence(org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.ONE, TESTRUN_0_0_0_9_0_0_0, TESTRUN_0_0_0_9_0_0_1, TESTRUN_0_0_0_9_0_0_2, TESTRUN_0_0_0_9_0_0_3, TESTRUN_0_0_0_9_0_0_4, TESTRUN_0_0_0_9_0_0_5);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunChoice TESTRUN_0_0_0_9_0 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunChoice(org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.ONE, TESTRUN_0_0_0_9_0_0);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCompound TESTRUN_0_0_0_9 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCompound(TESTRUN_0_0_0_9_0, org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.QUESTIONMARK);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunKeyword TESTRUN_0_0_0_10_0_0_0 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunKeyword("eachTestWithFullBattery", org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.ONE);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunWhiteSpace TESTRUN_0_0_0_10_0_0_1 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunWhiteSpace(1, org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.ONE);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunKeyword TESTRUN_0_0_0_10_0_0_2 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunKeyword(":", org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.ONE);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunWhiteSpace TESTRUN_0_0_0_10_0_0_3 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunWhiteSpace(1, org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.ONE);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunBooleanTerminal TESTRUN_0_0_0_10_0_0_4 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunBooleanTerminal(org.qualitune.jouleunit.android.testrun.TestrunPackage.eINSTANCE.getTestRun().getEStructuralFeature(org.qualitune.jouleunit.android.testrun.TestrunPackage.TEST_RUN__WAIT_FOR_FULL_BATTERY), "on", "off", org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.ONE, 0);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunLineBreak TESTRUN_0_0_0_10_0_0_5 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunLineBreak(org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.ONE, 0);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunSequence TESTRUN_0_0_0_10_0_0 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunSequence(org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.ONE, TESTRUN_0_0_0_10_0_0_0, TESTRUN_0_0_0_10_0_0_1, TESTRUN_0_0_0_10_0_0_2, TESTRUN_0_0_0_10_0_0_3, TESTRUN_0_0_0_10_0_0_4, TESTRUN_0_0_0_10_0_0_5);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunChoice TESTRUN_0_0_0_10_0 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunChoice(org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.ONE, TESTRUN_0_0_0_10_0_0);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCompound TESTRUN_0_0_0_10 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCompound(TESTRUN_0_0_0_10_0, org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.QUESTIONMARK);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunContainment TESTRUN_0_0_0_11_0_0_0 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunContainment(org.qualitune.jouleunit.android.testrun.TestrunPackage.eINSTANCE.getTestRun().getEStructuralFeature(org.qualitune.jouleunit.android.testrun.TestrunPackage.TEST_RUN__EXECUTABLES), org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.ONE, new org.eclipse.emf.ecore.EClass[] {org.qualitune.jouleunit.android.testrun.TestrunPackage.eINSTANCE.getTestExecutable(), }, 0);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunSequence TESTRUN_0_0_0_11_0_0 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunSequence(org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.ONE, TESTRUN_0_0_0_11_0_0_0);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunChoice TESTRUN_0_0_0_11_0 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunChoice(org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.ONE, TESTRUN_0_0_0_11_0_0);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCompound TESTRUN_0_0_0_11 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCompound(TESTRUN_0_0_0_11_0, org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.PLUS);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunSequence TESTRUN_0_0_0 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunSequence(org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.ONE, TESTRUN_0_0_0_0, TESTRUN_0_0_0_1, TESTRUN_0_0_0_2, TESTRUN_0_0_0_3, TESTRUN_0_0_0_4, TESTRUN_0_0_0_5, TESTRUN_0_0_0_6, TESTRUN_0_0_0_7, TESTRUN_0_0_0_8, TESTRUN_0_0_0_9, TESTRUN_0_0_0_10, TESTRUN_0_0_0_11);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunChoice TESTRUN_0_0 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunChoice(org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.ONE, TESTRUN_0_0_0);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunRule TESTRUN_0 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunRule(org.qualitune.jouleunit.android.testrun.TestrunPackage.eINSTANCE.getTestRun(), TESTRUN_0_0, org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.ONE);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunLineBreak TESTRUN_1_0_0_0 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunLineBreak(org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.ONE, 0);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunKeyword TESTRUN_1_0_0_1 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunKeyword("UnitTestCase", org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.ONE);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunWhiteSpace TESTRUN_1_0_0_2 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunWhiteSpace(1, org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.ONE);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunPlaceholder TESTRUN_1_0_0_3 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunPlaceholder(org.qualitune.jouleunit.android.testrun.TestrunPackage.eINSTANCE.getJunitTestCase().getEStructuralFeature(org.qualitune.jouleunit.android.testrun.TestrunPackage.JUNIT_TEST_CASE__NAME), "TESTID", org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.ONE, 0);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunSequence TESTRUN_1_0_0 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunSequence(org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.ONE, TESTRUN_1_0_0_0, TESTRUN_1_0_0_1, TESTRUN_1_0_0_2, TESTRUN_1_0_0_3);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunChoice TESTRUN_1_0 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunChoice(org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.ONE, TESTRUN_1_0_0);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunRule TESTRUN_1 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunRule(org.qualitune.jouleunit.android.testrun.TestrunPackage.eINSTANCE.getJunitTestCase(), TESTRUN_1_0, org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.ONE);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunLineBreak TESTRUN_2_0_0_0 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunLineBreak(org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.ONE, 0);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunKeyword TESTRUN_2_0_0_1 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunKeyword("TestSuite", org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.ONE);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunWhiteSpace TESTRUN_2_0_0_2 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunWhiteSpace(1, org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.ONE);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunPlaceholder TESTRUN_2_0_0_3 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunPlaceholder(org.qualitune.jouleunit.android.testrun.TestrunPackage.eINSTANCE.getTestSuite().getEStructuralFeature(org.qualitune.jouleunit.android.testrun.TestrunPackage.TEST_SUITE__NAME), "TEXT", org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.ONE, 0);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunWhiteSpace TESTRUN_2_0_0_4 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunWhiteSpace(1, org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.ONE);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunKeyword TESTRUN_2_0_0_5 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunKeyword("{", org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.ONE);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunLineBreak TESTRUN_2_0_0_6 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunLineBreak(org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.ONE, 0);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunLineBreak TESTRUN_2_0_0_7_0_0_0 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunLineBreak(org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.ONE, 1);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunKeyword TESTRUN_2_0_0_7_0_0_1 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunKeyword("SetUp", org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.ONE);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunWhiteSpace TESTRUN_2_0_0_7_0_0_2 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunWhiteSpace(1, org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.ONE);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunKeyword TESTRUN_2_0_0_7_0_0_3 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunKeyword("{", org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.ONE);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunLineBreak TESTRUN_2_0_0_7_0_0_4 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunLineBreak(org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.ONE, 2);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunContainment TESTRUN_2_0_0_7_0_0_5 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunContainment(org.qualitune.jouleunit.android.testrun.TestrunPackage.eINSTANCE.getTestSuite().getEStructuralFeature(org.qualitune.jouleunit.android.testrun.TestrunPackage.TEST_SUITE__SET_UP), org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.ONE, new org.eclipse.emf.ecore.EClass[] {org.qualitune.jouleunit.android.testrun.TestrunPackage.eINSTANCE.getTestBehavior(), }, 0);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunLineBreak TESTRUN_2_0_0_7_0_0_6 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunLineBreak(org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.ONE, 1);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunKeyword TESTRUN_2_0_0_7_0_0_7 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunKeyword("}", org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.ONE);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunLineBreak TESTRUN_2_0_0_7_0_0_8 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunLineBreak(org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.ONE, 0);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunSequence TESTRUN_2_0_0_7_0_0 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunSequence(org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.ONE, TESTRUN_2_0_0_7_0_0_0, TESTRUN_2_0_0_7_0_0_1, TESTRUN_2_0_0_7_0_0_2, TESTRUN_2_0_0_7_0_0_3, TESTRUN_2_0_0_7_0_0_4, TESTRUN_2_0_0_7_0_0_5, TESTRUN_2_0_0_7_0_0_6, TESTRUN_2_0_0_7_0_0_7, TESTRUN_2_0_0_7_0_0_8);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunChoice TESTRUN_2_0_0_7_0 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunChoice(org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.ONE, TESTRUN_2_0_0_7_0_0);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCompound TESTRUN_2_0_0_7 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCompound(TESTRUN_2_0_0_7_0, org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.QUESTIONMARK);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunLineBreak TESTRUN_2_0_0_8_0_0_0 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunLineBreak(org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.ONE, 1);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunKeyword TESTRUN_2_0_0_8_0_0_1 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunKeyword("TearDown", org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.ONE);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunWhiteSpace TESTRUN_2_0_0_8_0_0_2 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunWhiteSpace(1, org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.ONE);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunKeyword TESTRUN_2_0_0_8_0_0_3 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunKeyword("{", org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.ONE);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunLineBreak TESTRUN_2_0_0_8_0_0_4 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunLineBreak(org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.ONE, 2);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunContainment TESTRUN_2_0_0_8_0_0_5 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunContainment(org.qualitune.jouleunit.android.testrun.TestrunPackage.eINSTANCE.getTestSuite().getEStructuralFeature(org.qualitune.jouleunit.android.testrun.TestrunPackage.TEST_SUITE__TEAR_DOWN), org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.ONE, new org.eclipse.emf.ecore.EClass[] {org.qualitune.jouleunit.android.testrun.TestrunPackage.eINSTANCE.getTestBehavior(), }, 0);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunLineBreak TESTRUN_2_0_0_8_0_0_6 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunLineBreak(org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.ONE, 1);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunKeyword TESTRUN_2_0_0_8_0_0_7 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunKeyword("}", org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.ONE);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunLineBreak TESTRUN_2_0_0_8_0_0_8 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunLineBreak(org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.ONE, 0);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunSequence TESTRUN_2_0_0_8_0_0 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunSequence(org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.ONE, TESTRUN_2_0_0_8_0_0_0, TESTRUN_2_0_0_8_0_0_1, TESTRUN_2_0_0_8_0_0_2, TESTRUN_2_0_0_8_0_0_3, TESTRUN_2_0_0_8_0_0_4, TESTRUN_2_0_0_8_0_0_5, TESTRUN_2_0_0_8_0_0_6, TESTRUN_2_0_0_8_0_0_7, TESTRUN_2_0_0_8_0_0_8);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunChoice TESTRUN_2_0_0_8_0 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunChoice(org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.ONE, TESTRUN_2_0_0_8_0_0);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCompound TESTRUN_2_0_0_8 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCompound(TESTRUN_2_0_0_8_0, org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.QUESTIONMARK);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunLineBreak TESTRUN_2_0_0_9_0_0_0 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunLineBreak(org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.ONE, 1);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunContainment TESTRUN_2_0_0_9_0_0_1 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunContainment(org.qualitune.jouleunit.android.testrun.TestrunPackage.eINSTANCE.getTestSuite().getEStructuralFeature(org.qualitune.jouleunit.android.testrun.TestrunPackage.TEST_SUITE__EXECUTABLES), org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.ONE, new org.eclipse.emf.ecore.EClass[] {org.qualitune.jouleunit.android.testrun.TestrunPackage.eINSTANCE.getTestExecutable(), }, 0);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunLineBreak TESTRUN_2_0_0_9_0_0_2 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunLineBreak(org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.ONE, 0);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunSequence TESTRUN_2_0_0_9_0_0 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunSequence(org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.ONE, TESTRUN_2_0_0_9_0_0_0, TESTRUN_2_0_0_9_0_0_1, TESTRUN_2_0_0_9_0_0_2);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunChoice TESTRUN_2_0_0_9_0 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunChoice(org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.ONE, TESTRUN_2_0_0_9_0_0);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCompound TESTRUN_2_0_0_9 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCompound(TESTRUN_2_0_0_9_0, org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.PLUS);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunKeyword TESTRUN_2_0_0_10 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunKeyword("}", org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.ONE);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunSequence TESTRUN_2_0_0 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunSequence(org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.ONE, TESTRUN_2_0_0_0, TESTRUN_2_0_0_1, TESTRUN_2_0_0_2, TESTRUN_2_0_0_3, TESTRUN_2_0_0_4, TESTRUN_2_0_0_5, TESTRUN_2_0_0_6, TESTRUN_2_0_0_7, TESTRUN_2_0_0_8, TESTRUN_2_0_0_9, TESTRUN_2_0_0_10);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunChoice TESTRUN_2_0 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunChoice(org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.ONE, TESTRUN_2_0_0);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunRule TESTRUN_2 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunRule(org.qualitune.jouleunit.android.testrun.TestrunPackage.eINSTANCE.getTestSuite(), TESTRUN_2_0, org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.ONE);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunLineBreak TESTRUN_3_0_0_0 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunLineBreak(org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.ONE, 0);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunKeyword TESTRUN_3_0_0_1 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunKeyword("TestCase", org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.ONE);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunWhiteSpace TESTRUN_3_0_0_2 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunWhiteSpace(1, org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.ONE);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunPlaceholder TESTRUN_3_0_0_3 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunPlaceholder(org.qualitune.jouleunit.android.testrun.TestrunPackage.eINSTANCE.getTestCase().getEStructuralFeature(org.qualitune.jouleunit.android.testrun.TestrunPackage.TEST_CASE__NAME), "TEXT", org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.ONE, 0);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunWhiteSpace TESTRUN_3_0_0_4 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunWhiteSpace(1, org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.ONE);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunKeyword TESTRUN_3_0_0_5 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunKeyword("{", org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.ONE);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunLineBreak TESTRUN_3_0_0_6 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunLineBreak(org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.ONE, 1);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunContainment TESTRUN_3_0_0_7 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunContainment(org.qualitune.jouleunit.android.testrun.TestrunPackage.eINSTANCE.getTestCase().getEStructuralFeature(org.qualitune.jouleunit.android.testrun.TestrunPackage.TEST_CASE__BEHAVIOR), org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.ONE, new org.eclipse.emf.ecore.EClass[] {org.qualitune.jouleunit.android.testrun.TestrunPackage.eINSTANCE.getTestBehavior(), }, 0);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunLineBreak TESTRUN_3_0_0_8 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunLineBreak(org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.ONE, 0);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunKeyword TESTRUN_3_0_0_9 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunKeyword("}", org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.ONE);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunSequence TESTRUN_3_0_0 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunSequence(org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.ONE, TESTRUN_3_0_0_0, TESTRUN_3_0_0_1, TESTRUN_3_0_0_2, TESTRUN_3_0_0_3, TESTRUN_3_0_0_4, TESTRUN_3_0_0_5, TESTRUN_3_0_0_6, TESTRUN_3_0_0_7, TESTRUN_3_0_0_8, TESTRUN_3_0_0_9);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunChoice TESTRUN_3_0 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunChoice(org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.ONE, TESTRUN_3_0_0);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunRule TESTRUN_3 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunRule(org.qualitune.jouleunit.android.testrun.TestrunPackage.eINSTANCE.getTestCase(), TESTRUN_3_0, org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.ONE);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunContainment TESTRUN_4_0_0_0_0_0_0 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunContainment(org.qualitune.jouleunit.android.testrun.TestrunPackage.eINSTANCE.getBlock().getEStructuralFeature(org.qualitune.jouleunit.android.testrun.TestrunPackage.BLOCK__STATEMENTS), org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.ONE, new org.eclipse.emf.ecore.EClass[] {org.qualitune.jouleunit.android.testrun.TestrunPackage.eINSTANCE.getStatement(), }, 0);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunLineBreak TESTRUN_4_0_0_0_0_0_1 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunLineBreak(org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.ONE, 0);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunSequence TESTRUN_4_0_0_0_0_0 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunSequence(org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.ONE, TESTRUN_4_0_0_0_0_0_0, TESTRUN_4_0_0_0_0_0_1);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunChoice TESTRUN_4_0_0_0_0 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunChoice(org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.ONE, TESTRUN_4_0_0_0_0_0);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCompound TESTRUN_4_0_0_0 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCompound(TESTRUN_4_0_0_0_0, org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.STAR);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunSequence TESTRUN_4_0_0 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunSequence(org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.ONE, TESTRUN_4_0_0_0);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunChoice TESTRUN_4_0 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunChoice(org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.ONE, TESTRUN_4_0_0);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunRule TESTRUN_4 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunRule(org.qualitune.jouleunit.android.testrun.TestrunPackage.eINSTANCE.getBlock(), TESTRUN_4_0, org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.ONE);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunKeyword TESTRUN_5_0_0_0 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunKeyword("CLICK", org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.ONE);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunWhiteSpace TESTRUN_5_0_0_1 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunWhiteSpace(1, org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.ONE);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunKeyword TESTRUN_5_0_0_2 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunKeyword("ON", org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.ONE);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunWhiteSpace TESTRUN_5_0_0_3 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunWhiteSpace(1, org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.ONE);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunKeyword TESTRUN_5_0_0_4 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunKeyword("SCREEN", org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.ONE);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunWhiteSpace TESTRUN_5_0_0_5 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunWhiteSpace(1, org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.ONE);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunPlaceholder TESTRUN_5_0_0_6 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunPlaceholder(org.qualitune.jouleunit.android.testrun.TestrunPackage.eINSTANCE.getClickOnScreenStatement().getEStructuralFeature(org.qualitune.jouleunit.android.testrun.TestrunPackage.CLICK_ON_SCREEN_STATEMENT__X), "NUMBER", org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.ONE, 0);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunWhiteSpace TESTRUN_5_0_0_7 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunWhiteSpace(1, org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.ONE);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunPlaceholder TESTRUN_5_0_0_8 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunPlaceholder(org.qualitune.jouleunit.android.testrun.TestrunPackage.eINSTANCE.getClickOnScreenStatement().getEStructuralFeature(org.qualitune.jouleunit.android.testrun.TestrunPackage.CLICK_ON_SCREEN_STATEMENT__Y), "NUMBER", org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.ONE, 0);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunSequence TESTRUN_5_0_0 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunSequence(org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.ONE, TESTRUN_5_0_0_0, TESTRUN_5_0_0_1, TESTRUN_5_0_0_2, TESTRUN_5_0_0_3, TESTRUN_5_0_0_4, TESTRUN_5_0_0_5, TESTRUN_5_0_0_6, TESTRUN_5_0_0_7, TESTRUN_5_0_0_8);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunChoice TESTRUN_5_0 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunChoice(org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.ONE, TESTRUN_5_0_0);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunRule TESTRUN_5 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunRule(org.qualitune.jouleunit.android.testrun.TestrunPackage.eINSTANCE.getClickOnScreenStatement(), TESTRUN_5_0, org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.ONE);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunKeyword TESTRUN_6_0_0_0 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunKeyword("CURSOR", org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.ONE);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunPlaceholder TESTRUN_6_0_0_1 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunPlaceholder(org.qualitune.jouleunit.android.testrun.TestrunPackage.eINSTANCE.getCursorStatement().getEStructuralFeature(org.qualitune.jouleunit.android.testrun.TestrunPackage.CURSOR_STATEMENT__DIRECTION), "TEXT", org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.ONE, 0);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunSequence TESTRUN_6_0_0 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunSequence(org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.ONE, TESTRUN_6_0_0_0, TESTRUN_6_0_0_1);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunChoice TESTRUN_6_0 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunChoice(org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.ONE, TESTRUN_6_0_0);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunRule TESTRUN_6 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunRule(org.qualitune.jouleunit.android.testrun.TestrunPackage.eINSTANCE.getCursorStatement(), TESTRUN_6_0, org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.ONE);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunKeyword TESTRUN_7_0_0_0 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunKeyword("DISPLAY", org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.ONE);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunWhiteSpace TESTRUN_7_0_0_1 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunWhiteSpace(1, org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.ONE);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunBooleanTerminal TESTRUN_7_0_0_2 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunBooleanTerminal(org.qualitune.jouleunit.android.testrun.TestrunPackage.eINSTANCE.getDisplayStatement().getEStructuralFeature(org.qualitune.jouleunit.android.testrun.TestrunPackage.DISPLAY_STATEMENT__SWITCH_ON), "ON", "OFF", org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.ONE, 0);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunSequence TESTRUN_7_0_0 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunSequence(org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.ONE, TESTRUN_7_0_0_0, TESTRUN_7_0_0_1, TESTRUN_7_0_0_2);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunChoice TESTRUN_7_0 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunChoice(org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.ONE, TESTRUN_7_0_0);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunRule TESTRUN_7 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunRule(org.qualitune.jouleunit.android.testrun.TestrunPackage.eINSTANCE.getDisplayStatement(), TESTRUN_7_0, org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.ONE);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunKeyword TESTRUN_8_0_0_0 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunKeyword("ENTER", org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.ONE);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunSequence TESTRUN_8_0_0 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunSequence(org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.ONE, TESTRUN_8_0_0_0);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunChoice TESTRUN_8_0 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunChoice(org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.ONE, TESTRUN_8_0_0);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunRule TESTRUN_8 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunRule(org.qualitune.jouleunit.android.testrun.TestrunPackage.eINSTANCE.getEnterStatement(), TESTRUN_8_0, org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.ONE);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunKeyword TESTRUN_9_0_0_0 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunKeyword("HOME", org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.ONE);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunWhiteSpace TESTRUN_9_0_0_1 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunWhiteSpace(1, org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.ONE);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunKeyword TESTRUN_9_0_0_2 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunKeyword("BUTTON", org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.ONE);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunSequence TESTRUN_9_0_0 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunSequence(org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.ONE, TESTRUN_9_0_0_0, TESTRUN_9_0_0_1, TESTRUN_9_0_0_2);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunChoice TESTRUN_9_0 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunChoice(org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.ONE, TESTRUN_9_0_0);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunRule TESTRUN_9 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunRule(org.qualitune.jouleunit.android.testrun.TestrunPackage.eINSTANCE.getHomeButtonStatement(), TESTRUN_9_0, org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.ONE);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunKeyword TESTRUN_10_0_0_0 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunKeyword("OPEN", org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.ONE);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunWhiteSpace TESTRUN_10_0_0_1 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunWhiteSpace(1, org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.ONE);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunKeyword TESTRUN_10_0_0_2 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunKeyword("SETTINGS", org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.ONE);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunSequence TESTRUN_10_0_0 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunSequence(org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.ONE, TESTRUN_10_0_0_0, TESTRUN_10_0_0_1, TESTRUN_10_0_0_2);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunChoice TESTRUN_10_0 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunChoice(org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.ONE, TESTRUN_10_0_0);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunRule TESTRUN_10 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunRule(org.qualitune.jouleunit.android.testrun.TestrunPackage.eINSTANCE.getOpenSettingsStatement(), TESTRUN_10_0, org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.ONE);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunKeyword TESTRUN_11_0_0_0 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunKeyword("SEND", org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.ONE);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunWhiteSpace TESTRUN_11_0_0_1 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunWhiteSpace(1, org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.ONE);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunKeyword TESTRUN_11_0_0_2 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunKeyword("MESSAGE", org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.ONE);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunWhiteSpace TESTRUN_11_0_0_3 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunWhiteSpace(1, org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.ONE);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunPlaceholder TESTRUN_11_0_0_4 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunPlaceholder(org.qualitune.jouleunit.android.testrun.TestrunPackage.eINSTANCE.getSendPortMessageStatement().getEStructuralFeature(org.qualitune.jouleunit.android.testrun.TestrunPackage.SEND_PORT_MESSAGE_STATEMENT__IP), "QUOTED_34_34", org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.ONE, 0);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunWhiteSpace TESTRUN_11_0_0_5 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunWhiteSpace(1, org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.ONE);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunPlaceholder TESTRUN_11_0_0_6 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunPlaceholder(org.qualitune.jouleunit.android.testrun.TestrunPackage.eINSTANCE.getSendPortMessageStatement().getEStructuralFeature(org.qualitune.jouleunit.android.testrun.TestrunPackage.SEND_PORT_MESSAGE_STATEMENT__PORT), "NUMBER", org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.ONE, 0);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunWhiteSpace TESTRUN_11_0_0_7 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunWhiteSpace(1, org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.ONE);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunPlaceholder TESTRUN_11_0_0_8 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunPlaceholder(org.qualitune.jouleunit.android.testrun.TestrunPackage.eINSTANCE.getSendPortMessageStatement().getEStructuralFeature(org.qualitune.jouleunit.android.testrun.TestrunPackage.SEND_PORT_MESSAGE_STATEMENT__MESSAGE), "QUOTED_34_34", org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.ONE, 0);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunSequence TESTRUN_11_0_0 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunSequence(org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.ONE, TESTRUN_11_0_0_0, TESTRUN_11_0_0_1, TESTRUN_11_0_0_2, TESTRUN_11_0_0_3, TESTRUN_11_0_0_4, TESTRUN_11_0_0_5, TESTRUN_11_0_0_6, TESTRUN_11_0_0_7, TESTRUN_11_0_0_8);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunChoice TESTRUN_11_0 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunChoice(org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.ONE, TESTRUN_11_0_0);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunRule TESTRUN_11 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunRule(org.qualitune.jouleunit.android.testrun.TestrunPackage.eINSTANCE.getSendPortMessageStatement(), TESTRUN_11_0, org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.ONE);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunKeyword TESTRUN_12_0_0_0 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunKeyword("START", org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.ONE);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunWhiteSpace TESTRUN_12_0_0_1 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunWhiteSpace(1, org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.ONE);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunKeyword TESTRUN_12_0_0_2 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunKeyword("ACTIVITY", org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.ONE);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunWhiteSpace TESTRUN_12_0_0_3 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunWhiteSpace(1, org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.ONE);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunPlaceholder TESTRUN_12_0_0_4 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunPlaceholder(org.qualitune.jouleunit.android.testrun.TestrunPackage.eINSTANCE.getStartActivityStatement().getEStructuralFeature(org.qualitune.jouleunit.android.testrun.TestrunPackage.START_ACTIVITY_STATEMENT__PACKAGE), "QUOTED_34_34", org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.ONE, 0);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunWhiteSpace TESTRUN_12_0_0_5 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunWhiteSpace(1, org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.ONE);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunPlaceholder TESTRUN_12_0_0_6 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunPlaceholder(org.qualitune.jouleunit.android.testrun.TestrunPackage.eINSTANCE.getStartActivityStatement().getEStructuralFeature(org.qualitune.jouleunit.android.testrun.TestrunPackage.START_ACTIVITY_STATEMENT__CLASS), "QUOTED_34_34", org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.ONE, 0);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunSequence TESTRUN_12_0_0 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunSequence(org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.ONE, TESTRUN_12_0_0_0, TESTRUN_12_0_0_1, TESTRUN_12_0_0_2, TESTRUN_12_0_0_3, TESTRUN_12_0_0_4, TESTRUN_12_0_0_5, TESTRUN_12_0_0_6);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunChoice TESTRUN_12_0 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunChoice(org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.ONE, TESTRUN_12_0_0);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunRule TESTRUN_12 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunRule(org.qualitune.jouleunit.android.testrun.TestrunPackage.eINSTANCE.getStartActivityStatement(), TESTRUN_12_0, org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.ONE);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunKeyword TESTRUN_13_0_0_0 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunKeyword("WAIT", org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.ONE);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunWhiteSpace TESTRUN_13_0_0_1 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunWhiteSpace(1, org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.ONE);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunKeyword TESTRUN_13_0_0_2 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunKeyword("FOR", org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.ONE);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunWhiteSpace TESTRUN_13_0_0_3 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunWhiteSpace(1, org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.ONE);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunPlaceholder TESTRUN_13_0_0_4 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunPlaceholder(org.qualitune.jouleunit.android.testrun.TestrunPackage.eINSTANCE.getWaitStatement().getEStructuralFeature(org.qualitune.jouleunit.android.testrun.TestrunPackage.WAIT_STATEMENT__SECONDS), "NUMBER", org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.ONE, 0);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunSequence TESTRUN_13_0_0 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunSequence(org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.ONE, TESTRUN_13_0_0_0, TESTRUN_13_0_0_1, TESTRUN_13_0_0_2, TESTRUN_13_0_0_3, TESTRUN_13_0_0_4);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunChoice TESTRUN_13_0 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunChoice(org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.ONE, TESTRUN_13_0_0);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunRule TESTRUN_13 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunRule(org.qualitune.jouleunit.android.testrun.TestrunPackage.eINSTANCE.getWaitStatement(), TESTRUN_13_0, org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.ONE);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunKeyword TESTRUN_14_0_0_0 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunKeyword("UNLOCK", org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.ONE);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunSequence TESTRUN_14_0_0 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunSequence(org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.ONE, TESTRUN_14_0_0_0);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunChoice TESTRUN_14_0 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunChoice(org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.ONE, TESTRUN_14_0_0);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunRule TESTRUN_14 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunRule(org.qualitune.jouleunit.android.testrun.TestrunPackage.eINSTANCE.getUnlockStatement(), TESTRUN_14_0, org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.ONE);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunKeyword TESTRUN_15_0_0_0 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunKeyword("Test", org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.ONE);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunWhiteSpace TESTRUN_15_0_0_1 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunWhiteSpace(1, org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.ONE);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunPlaceholder TESTRUN_15_0_0_2 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunPlaceholder(org.qualitune.jouleunit.android.testrun.TestrunPackage.eINSTANCE.getTestStatement().getEStructuralFeature(org.qualitune.jouleunit.android.testrun.TestrunPackage.TEST_STATEMENT__NAME), "TEXT", org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.ONE, 0);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunLineBreak TESTRUN_15_0_0_3_0_0_0 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunLineBreak(org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.ONE, 1);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunContainment TESTRUN_15_0_0_3_0_0_1 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunContainment(org.qualitune.jouleunit.android.testrun.TestrunPackage.eINSTANCE.getTestStatement().getEStructuralFeature(org.qualitune.jouleunit.android.testrun.TestrunPackage.TEST_STATEMENT__STATEMENTS), org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.ONE, new org.eclipse.emf.ecore.EClass[] {org.qualitune.jouleunit.android.testrun.TestrunPackage.eINSTANCE.getStatement(), }, 0);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunLineBreak TESTRUN_15_0_0_3_0_0_2 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunLineBreak(org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.ONE, 0);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunSequence TESTRUN_15_0_0_3_0_0 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunSequence(org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.ONE, TESTRUN_15_0_0_3_0_0_0, TESTRUN_15_0_0_3_0_0_1, TESTRUN_15_0_0_3_0_0_2);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunWhiteSpace TESTRUN_15_0_0_3_0_1_0 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunWhiteSpace(1, org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.ONE);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunKeyword TESTRUN_15_0_0_3_0_1_1 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunKeyword("{", org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.ONE);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunLineBreak TESTRUN_15_0_0_3_0_1_2_0_0_0 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunLineBreak(org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.ONE, 1);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunContainment TESTRUN_15_0_0_3_0_1_2_0_0_1 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunContainment(org.qualitune.jouleunit.android.testrun.TestrunPackage.eINSTANCE.getTestStatement().getEStructuralFeature(org.qualitune.jouleunit.android.testrun.TestrunPackage.TEST_STATEMENT__STATEMENTS), org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.ONE, new org.eclipse.emf.ecore.EClass[] {org.qualitune.jouleunit.android.testrun.TestrunPackage.eINSTANCE.getStatement(), }, 0);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunSequence TESTRUN_15_0_0_3_0_1_2_0_0 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunSequence(org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.ONE, TESTRUN_15_0_0_3_0_1_2_0_0_0, TESTRUN_15_0_0_3_0_1_2_0_0_1);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunChoice TESTRUN_15_0_0_3_0_1_2_0 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunChoice(org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.ONE, TESTRUN_15_0_0_3_0_1_2_0_0);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCompound TESTRUN_15_0_0_3_0_1_2 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCompound(TESTRUN_15_0_0_3_0_1_2_0, org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.PLUS);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunLineBreak TESTRUN_15_0_0_3_0_1_3 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunLineBreak(org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.ONE, 0);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunKeyword TESTRUN_15_0_0_3_0_1_4 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunKeyword("}", org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.ONE);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunSequence TESTRUN_15_0_0_3_0_1 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunSequence(org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.ONE, TESTRUN_15_0_0_3_0_1_0, TESTRUN_15_0_0_3_0_1_1, TESTRUN_15_0_0_3_0_1_2, TESTRUN_15_0_0_3_0_1_3, TESTRUN_15_0_0_3_0_1_4);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunChoice TESTRUN_15_0_0_3_0 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunChoice(org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.ONE, TESTRUN_15_0_0_3_0_0, TESTRUN_15_0_0_3_0_1);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCompound TESTRUN_15_0_0_3 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCompound(TESTRUN_15_0_0_3_0, org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.ONE);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunSequence TESTRUN_15_0_0 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunSequence(org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.ONE, TESTRUN_15_0_0_0, TESTRUN_15_0_0_1, TESTRUN_15_0_0_2, TESTRUN_15_0_0_3);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunChoice TESTRUN_15_0 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunChoice(org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.ONE, TESTRUN_15_0_0);
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunRule TESTRUN_15 = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunRule(org.qualitune.jouleunit.android.testrun.TestrunPackage.eINSTANCE.getTestStatement(), TESTRUN_15_0, org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunCardinality.ONE);
	
	public static String getSyntaxElementID(org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunSyntaxElement syntaxElement) {
		if (syntaxElement == null) {
			// null indicates EOF
			return "<EOF>";
		}
		for (java.lang.reflect.Field field : org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunGrammarInformationProvider.class.getFields()) {
			Object fieldValue;
			try {
				fieldValue = field.get(null);
				if (fieldValue == syntaxElement) {
					String id = field.getName();
					return id;
				}
			} catch (Exception e) { }
		}
		return null;
	}
	
	public static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunSyntaxElement getSyntaxElementByID(String syntaxElementID) {
		try {
			return (org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunSyntaxElement) org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunGrammarInformationProvider.class.getField(syntaxElementID).get(null);
		} catch (Exception e) {
			return null;
		}
	}
	
	public final static org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunRule[] RULES = new org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunRule[] {
		TESTRUN_0,
		TESTRUN_1,
		TESTRUN_2,
		TESTRUN_3,
		TESTRUN_4,
		TESTRUN_5,
		TESTRUN_6,
		TESTRUN_7,
		TESTRUN_8,
		TESTRUN_9,
		TESTRUN_10,
		TESTRUN_11,
		TESTRUN_12,
		TESTRUN_13,
		TESTRUN_14,
		TESTRUN_15,
	};
	
	/**
	 * Returns all keywords of the grammar. This includes all literals for boolean and
	 * enumeration terminals.
	 */
	public java.util.Set<String> getKeywords() {
		if (this.keywords == null) {
			this.keywords = new java.util.LinkedHashSet<String>();
			for (org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunRule rule : RULES) {
				findKeywords(rule, this.keywords);
			}
		}
		return keywords;
	}
	
	/**
	 * Finds all keywords in the given element and its children and adds them to the
	 * set. This includes all literals for boolean and enumeration terminals.
	 */
	private void findKeywords(org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunSyntaxElement element, java.util.Set<String> keywords) {
		if (element instanceof org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunKeyword) {
			keywords.add(((org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunKeyword) element).getValue());
		} else if (element instanceof org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunBooleanTerminal) {
			keywords.add(((org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunBooleanTerminal) element).getTrueLiteral());
			keywords.add(((org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunBooleanTerminal) element).getFalseLiteral());
		} else if (element instanceof org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunEnumerationTerminal) {
			org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunEnumerationTerminal terminal = (org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunEnumerationTerminal) element;
			for (String key : terminal.getLiteralMapping().keySet()) {
				keywords.add(key);
			}
		}
		for (org.qualitune.jouleunit.android.testrun.resource.testrun.grammar.TestrunSyntaxElement child : element.getChildren()) {
			findKeywords(child, this.keywords);
		}
	}
	
}
